### ISSUE TITLE
Erreur répétitive 'NoneType' object has no attribute 'create_task'

### ISSUE THREAD

**Issue by jduquennoy** [hekmon/linkytic#33]
**Commit installé:** d8a210b8bdc1baba49fb411504085ad8b9c655fa
**Configuration:** Standard, mode temps réel activé
**Version de HomeAssistant Core:** 2024.2.4

**Description:**
Dans les logs de mon instance HA, j'observe le log ci dessous.
Les données sont bien remontées par l'intégration, y compris les valeurs en temps réelle (la puissance instantanée notamment).
Je n'ai malheureusement pas beaucoup de temps pour analyser le problème de mon côté, mais je suis dispo pour faire des essais ou donner plus d'information si nécessaire.

**Logs**
```
2024-02-27 16:38:42.835 ERROR (LinkyTIC for /dev/serial/by-id/usb-Silicon_Labs_LinkyTIC_0001-if00-port0) [custom_components.linkytic.serial_reader] encountered an unexpected exception on the serial thread, catching it to avoid thread crash: 'NoneType' object has no attribute 'create_task'
Traceback (most recent call last):
File "/config/custom_components/linkytic/serial_reader.py", line 151, in run
notif_callback(forced_update)
File "/config/custom_components/linkytic/sensor.py", line 1649, in update_notification
self.schedule_update_ha_state(force_refresh=True)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1199, in schedule_update_ha_state
self.hass.create_task(
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_task'
```

**Comment by hekmon** [comment]
Mmmm donc `self.hass` ne serait pas initialisé... J'ai regardé mes logs sur plusieurs mois, aucune occurence de ce problème.

Est-ce toujours le cas chez vous ?

**Comment by Lunaden** [comment]
J'ai personnellement le même problème sauf que les valeurs récupérées ne s'incrémentent pas (avec ou sans l'option temps réel) sauf en redémarrant le plugin.
